language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.5-dev"
- "nightly"
env:
 - DJANGO_VERSION==1.10
install:
 - pip install -q Django=$DJANGO_VERSION
 - python SquarensquareCI.py -q run
script: nosetests
